import { tags } from "typia";

/**
 * Favorite address entity for a buyer/seller: links a user to a shipping or
 * billing address with organization/folder, label, and primary flags. Includes
 * snapshot for evidence.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IAiCommerceFavoritesAddress = {
  /** Unique identifier for this favorite address record. */
  id: string & tags.Format<"uuid">;

  /**
   * UUID referencing the buyer or seller account that owns this address
   * favorite.
   */
  user_id: string & tags.Format<"uuid">;

  /** UUID of the user address that is being favorited. */
  address_id: string & tags.Format<"uuid">;

  /**
   * Optional UUID of the organizing folder this favorite belongs to. Null if
   * not grouped.
   */
  folder_id?: (string & tags.Format<"uuid">) | null | undefined;

  /** UUID of the address snapshot entity captured at favoriting. */
  snapshot_id: string & tags.Format<"uuid">;

  /**
   * Optional label set by user for organization/searching (e.g., 'Home',
   * 'Company').
   */
  label?: string | null | undefined;

  /**
   * Whether this address favorite is marked as the primary one in user's
   * personal context.
   */
  primary: boolean;

  /** Timestamp (ISO 8601) when the favorite address record was created. */
  created_at: string & tags.Format<"date-time">;

  /** Timestamp for the last update to this favorite address record. */
  updated_at: string & tags.Format<"date-time">;

  /** Soft delete timestamp for logical removal (null if active). */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IAiCommerceFavoritesAddress {
  /**
   * Filtering parameters for searching a user's favorite addresses. Enables
   * UI to organize, query, and display paginated address favorites. Supports
   * filtering by folder, label, primary status, address identity, and
   * sorting/pagination.
   */
  export type IRequest = {
    /**
     * Optional filter to return only favorite addresses in the specified
     * organizational folder (UUID). Use for user-facing organization and UI
     * navigation.
     */
    folder_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Optional filter for searching labels attached to favorite addresses.
     * Returns favorites containing the substring as a label.
     */
    label?: string | undefined;

    /**
     * If true, filter the result to only addresses marked as primary
     * favorites. Used in checkout and fast access scenarios.
     */
    primary?: boolean | undefined;

    /**
     * Optional filter to search favorite addresses linked to a particular
     * address entry (UUID).
     */
    address_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Sort order, e.g., 'created_at desc', 'label asc'. If omitted,
     * defaults to creation date descending.
     */
    sort?: string | undefined;

    /** Page number for pagination, 1-based index (default: 1). */
    page?: (number & tags.Type<"int32">) | undefined;

    /** Page size for pagination; maximum records per page (default: 20). */
    limit?: (number & tags.Type<"int32">) | undefined;
  };

  /**
   * Defines the payload for favoriting a user address and organizing it for
   * rapid/AI-driven checkout, notifications, organization, or recovery.
   */
  export type ICreate = {
    /**
     * The UUID of the address entity to favorite. Must already exist and
     * belong to the user.
     */
    address_id: string & tags.Format<"uuid">;

    /**
     * Optional UUID for the organization folder to include this favorite
     * in.
     */
    folder_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Optional user label for personal reference/organization (e.g.,
     * 'Gift', 'Grandma').
     */
    label?: string | undefined;

    /**
     * Flag to mark this address as the primary favorite for user (optional,
     * default false).
     */
    primary?: boolean | undefined;
  };

  /**
   * Request body for updating (relabeling or reorganizing) a user's favorite
   * address. Only folder, label, or primary status can be changed.
   */
  export type IUpdate = {
    /**
     * UUID of the new folder to move this favorite address to (if changing
     * organization).
     */
    folder_id?: (string & tags.Format<"uuid">) | undefined;

    /** Update or assign a personal label to this favorite address. */
    label?: string | undefined;

    /**
     * Set/unset this address as the primary favorite in user's
     * organizational context.
     */
    primary?: boolean | undefined;
  };

  /**
   * Summary/grouping view of a user's favorited address, with linkage to
   * owner, address reference, label, snapshot, and primary flag. Used in
   * personalized address management dashboards.
   */
  export type ISummary = {
    /** UUID for the favorite-address record. */
    id: string & tags.Format<"uuid">;

    /** UUID for the owner of the favorite (buyer or seller, as allowed). */
    user_id: string;

    /**
     * UUID of the user address being favorited
     * (ai_commerce_user_addresses.id).
     */
    address_id: string;

    /**
     * UUID of favorite's point-in-time snapshot (immutable copy of address
     * at the time of favoriting).
     */
    snapshot_id: string;

    /**
     * Descriptive label/annotation for organization/search within the
     * user's favorites.
     */
    label: string | null;

    /**
     * Indicates whether this favorite is designated primary for the user.
     * Only one favorite address may be primary per user.
     */
    primary: boolean;

    /** ISO 8601 timestamp when address was favorited. */
    created_at: string;

    /**
     * ISO 8601 timestamp when favorite was last updated
     * (label/folder/metadata change).
     */
    updated_at: string;

    /**
     * If the favorite address is deleted, this contains the soft delete
     * timestamp (ISO 8601); null if active.
     */
    deleted_at: string | null;
  };
}
