import { tags } from "typia";

/**
 * Product image record for a product, as in ai_commerce_product_images table.
 * Includes all persisted fields and metadata for UI/photo gallery rendering.
 * Used as response type for image detail and image list/indexing endpoints.
 * References only persisted properties as described in schema. Does not include
 * attachment metadata—see IAiCommerceAttachment for file information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IAiCommerceProductImage = {
  /**
   * Unique identifier of the product image record as stored in
   * ai_commerce_product_images. Always a UUID.
   */
  id: string & tags.Format<"uuid">;

  /**
   * UUID of the parent product this image belongs to. References
   * ai_commerce_products.id.
   */
  product_id: string & tags.Format<"uuid">;

  /**
   * UUID identifying the uploaded attachment file linked to this image.
   * References ai_commerce_attachments.id.
   */
  attachment_id: string & tags.Format<"uuid">;

  /**
   * Numeric order (ascending) for this image in product image arrays. Used
   * for primary image selection and gallery sequencing.
   */
  display_order: number & tags.Type<"int32">;

  /**
   * Optional locale of the image if localized, null/default for
   * non-localized.
   */
  locale?: string | null | undefined;
};
export namespace IAiCommerceProductImage {
  /**
   * Request body for paginating and searching product images associated with
   * a product.
   *
   * Supports filtering by product, locale, and supports sort and pagination
   * for large product image galleries.
   */
  export type IRequest = {
    /** UUID of the parent product to filter images for. */
    productId?: string | undefined;

    /**
     * Locale/language code to filter displayed image versions (e.g.,
     * 'en-US', 'ko-KR').
     */
    locale?: string | undefined;

    /** Sort field for image selection. */
    sort?: string | undefined;

    /** Sort order. */
    order?: "asc" | "desc" | undefined;

    /** Page number for paginated results. */
    page?: (number & tags.Type<"int32">) | undefined;

    /** Records per page for pagination. */
    limit?: (number & tags.Type<"int32">) | undefined;
  };

  /**
   * Request body for creating a new product image record linked to a product.
   * Used for admin or seller routes for uploading/associating images.
   * Required fields are defined in the database schema.
   */
  export type ICreate = {
    /**
     * UUID of the parent product for which this image is being uploaded.
     * Must reference an existing ai_commerce_products.id.
     */
    product_id: string & tags.Format<"uuid">;

    /**
     * UUID identifier of the attachment being referenced as the image
     * source. Must reference an existing ai_commerce_attachments.id.
     */
    attachment_id: string & tags.Format<"uuid">;

    /**
     * Display order (ascending) for this image in the product's image
     * gallery. 0 indicates the primary/default image. Used for UI sorting.
     */
    display_order: number & tags.Type<"int32">;

    /**
     * Optional locale (e.g., en-US, ko-KR) for localization of images in
     * multi-region catalogs. If omitted or null, image is default/global.
     */
    locale?: string | null | undefined;
  };

  /**
   * Request body for updating an existing product image. Only supplied fields
   * are updated; omitted properties are unchanged. Used for PATCH/PUT
   * endpoints by admin or seller. Keys must conform to the property types and
   * constraints described in the schema.
   */
  export type IUpdate = {
    /**
     * If supplied, updates the linked attachment file for this product
     * image. Must reference an existing ai_commerce_attachments.id.
     */
    attachment_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * If supplied, updates the display/sort order of this image in the
     * product gallery.
     */
    display_order?: (number & tags.Type<"int32">) | undefined;

    /**
     * If supplied, updates the locale/region code for this image. Null
     * clears localization.
     */
    locale?: string | null | undefined;
  };

  /**
   * Summary of a product image entity as presented in list views. Contains
   * only the fields necessary for listing/ordering in product image gallery
   * or for preview in admin/seller management screens. No nesting or asset
   * data—use attachment_id to link to actual file data.
   */
  export type ISummary = {
    /** Image UUID as per product image entity. */
    id: string & tags.Format<"uuid">;

    /** Display order in product image set (ascending). */
    display_order: number & tags.Type<"int32">;

    /**
     * Optional locale of the image, will be null for default
     * language/region.
     */
    locale: string | null;

    /** Attachment UUID for the underlying physical image file. */
    attachment_id: string & tags.Format<"uuid">;
  };
}
