import { IPage } from "./IPage";
import { IAimallBackendCouponRedemption } from "./IAimallBackendCouponRedemption";

/**
 * Paginated set of coupon redemption event records. Used for analytics, fraud
 * audit, and campaign reporting. Contains both pagination metadata and the
 * array of event/list entries per schema.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIAimallBackendCouponRedemption = {
  pagination: IPage.IPagination;
  data: IAimallBackendCouponRedemption[];
};
