import { IPage } from "./IPage";
import { IAdminAssignment } from "./IAdminAssignment";

/**
 * 관리자 역할 종속 RBAC 할당(assignment) 검색 결과의 페이지 컨테이너입니다.
 *
 * IPage 명세(표준) 및 admin_assignments 엔티티 구조를 따릅니다. 페이징 메타 + 할당 row 리스트를 모두 포함.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIAdminAssignment = {
  pagination: IPage.IPagination;

  /** 관리자 역할/권한 할당 레코드 집합 */
  data: IAdminAssignment[];
};
