import { IPage } from "./IPage";
import { IUserProfile } from "./IUserProfile";

/**
 * 사용자 프로필 목록의 페이지 응답 타입입니다.
 *
 * 이 타입은 복수의 사용자 프로필을 페이지네이션 방식으로 조회할 때 반환하는 구조로, 개별 사용자 프로필(UserProfile) 정보와
 * 페이지네이션 메타데이터를 함께 제공합니다.
 *
 * 원본 Prisma DB의 user_profiles 테이블 전체 레코드를 대상으로 페이지 단위로 조회하는 경우 사용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageUserProfile = {
  /**
   * 페이지네이션 정보입니다. 전체 결과 중 현재 페이지의 위치, 한 페이지당 항목 수, 전체 항목 수, 전체 페이지 수 등이
   * 포함됩니다.
   *
   * 이 정보는 리스트 API의 페이징 처리를 위해 필요하며, 실제 데이터와 함께 반환됩니다.
   */
  pagination: IPage.IPagination;

  /**
   * 해당 페이지에 포함된 사용자 프로필(UserProfile) 데이터의 배열입니다.
   *
   * 각 배열 요소는 IUserProfile 타입의 객체로, 사용자별 상세 정보를 포함합니다.
   */
  data: IUserProfile[];
};
