import { IPage } from "./IPage";
import { IRbacPermission } from "./IRbacPermission";

/**
 * RBAC 권한 목록에 대한 페이지네이션 결과 컨테이너.
 *
 * Pagination 필드에는 현재 페이지, 총 레코드, 제한값 등이 포함되고, data 필드는 IRbacPermission 객체 리스트를
 * 포함합니다.
 *
 * 권한 관리, 감사, 시스템 설정 관리 등 관리자 또는 컴플라이언스 목적의 대규모 권한 정보 조회에 사용됩니다.
 *
 * Prisma DB 스키마와 IPage 형식을 모두 준수합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIRbacPermission = {
  pagination: IPage.IPagination;

  /** 요청 조건에 따라 필터링된 RBAC 권한 엔티티 목록입니다. */
  data: IRbacPermission[];
};
