import { IPage } from "./IPage";
import { IShoppingMallAiBackendSeller } from "./IShoppingMallAiBackendSeller";

/**
 * Paginated result for full seller records, not only summaries.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIShoppingMallAiBackendSeller = {
  /** Record count, current, limit/count, and pages for the returned set. */
  pagination: IPage.IPagination;

  /** Array of seller entities. */
  data: IShoppingMallAiBackendSeller[];
};
export namespace IPageIShoppingMallAiBackendSeller {
  /** Paginated results for seller search/listing (summary variant). */
  export type ISummary = {
    /** Pagination metadata. */
    pagination: IPage.IPagination;

    /** Paged array of summarized seller records. */
    data: IShoppingMallAiBackendSeller.ISummary[];
  };
}
