import { IPage } from "./IPage";
import { IUserBalance } from "./IUserBalance";

/**
 * 사용자 잔액 정보의 페이지네이션 응답 구조체
 *
 * - Pagination : 현재 페이지 정보, 전체 갯수 등 메타
 * - Data : 특정 조건/페이지별 실제 사용자 잔고 엔트리
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIUserBalance = {
  pagination: IPage.IPagination;

  /**
   * 실제 조회 및 반환된 사용자 잔고 목록 데이터 배열입니다.
   *
   * 각 오브젝트는 IUserBalance 스키마에 따라 직렬화됩니다.
   */
  data: IUserBalance[];
};
