import { IPage } from "./IPage";
import { IProductMedia } from "./IProductMedia";

/**
 * Paginated page response for product media assets, each item referencing
 * attachment metadata and gallery configuration.
 *
 * Standard IPage<T> container for rendering or reporting large product
 * galleries.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIProductMedia = {
  pagination: IPage.IPagination;

  /**
   * Media objects for product (image/video/doc metadata for catalog display,
   * admin review, or compliance download).
   */
  data: IProductMedia[];
};
