import { IPage } from "./IPage";
import { IShoppingMallAiBackendProductFile } from "./IShoppingMallAiBackendProductFile";

/**
 * Paginated listing of product file resources. The data field is always an
 * array of `IShoppingMallAiBackendProductFile.ISummary` as required by IPage
 * pattern.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIShoppingMallAiBackendProductFile = {
  /** Pagination information. */
  pagination: IPage.IPagination;

  /** Array of product file summaries on this page. */
  data: IShoppingMallAiBackendProductFile.ISummary[];
};
