import { IPage } from "./IPage";
import { IAimallBackendOrder } from "./IAimallBackendOrder";

/**
 * Paginated result page for order entities. Supports listing on administrative
 * and seller dashboards, as well as customer order history. Contains a
 * pagination object and an array of complete order entity records.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIAimallBackendOrder = {
  pagination: IPage.IPagination;
  data: IAimallBackendOrder[];
};
