import { IPage } from "./IPage";
import { IFraudCheck } from "./IFraudCheck";

/**
 * FraudCheck(사기 탐지/리스크 평가 기록) 엔티티의 페이지네이션 응답 타입.
 *
 * 표준 IPage 구조 사용. 페이징/검색 결과 등에서 사용되며, data는 IFraudCheck의 배열입니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIFraudCheck = {
  pagination: IPage.IPagination;

  /** FraudCheck 엔티티의 결과 리스트. 페이지네이션 결과(복수)입니다. */
  data: IFraudCheck[];
};
