import { IPage } from "./IPage";
import { IProductOption } from "./IProductOption";

/**
 * Paginated result envelope for product option listings in search or batch list
 * APIs. Wraps an array of IProductOption records with full pagination meta, as
 * per the IPage<T> contract used across all list APIs.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIProductOption = {
  /**
   * Pagination info for the returned collection. Describes
   * page/limit/total/pages as in the IPage standard.
   */
  pagination?: IPage.IPagination;

  /** Array of product option entities in the current page of results. */
  data?: IProductOption[];
};
