import { IPage } from "./IPage";
import { IAimallBackendAddress } from "./IAimallBackendAddress";

/**
 * Paginated results of addresses (customer delivery addresses). Used for
 * address books and selection.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIAimallBackendAddress = {
  pagination: IPage.IPagination;
  data: IAimallBackendAddress[];
};
