import { IPage } from "./IPage";
import { ICartTemplate } from "./ICartTemplate";

/**
 * 카트(재사용) 템플릿 목록의 페이지 응답 타입입니다.
 *
 * 여러 템플릿 레코드와 페이징 정보를 함께 제공합니다. 반복구매, 자주쓰는 장바구니 보관함 리스트 화면 등에 사용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICartTemplate = {
  /**
   * 페이지네이션 정보.
   *
   * 전체 레코드 수, 현재페이지, 페이지 당 limit, 페이지 개수 정보 포함. 템플릿이 많은 경우 효과적으로 페이징을 지원합니다.
   */
  pagination: IPage.IPagination;

  /**
   * 카트 템플릿 데이터의 배열입니다.
   *
   * 각 템플릿의 상세 정보(ICartTemplate)를 담습니다.
   */
  data: ICartTemplate[];
};
