import { IPage } from "./IPage";
import { IUserExternalAuth } from "./IUserExternalAuth";

/**
 * Result format for paginated responses when searching user_external_auths.
 *
 * Includes pagination meta and array of user external authentication mappings.
 * Each record confirms link between system user and an external auth provider.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIUserExternalAuth = {
  pagination: IPage.IPagination;
  data: IUserExternalAuth[];
};
