import { IPage } from "./IPage";
import { IOrderItem } from "./IOrderItem";

/**
 * Paginated container for order items.
 *
 * This structure is used for paginating the results – holding an array of order
 * items and describing pagination state. Implements the IPage<T> pattern across
 * the API.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIOrderItem = {
  /**
   * Pagination information for the page: current page, limit, total records,
   * total pages.
   */
  pagination: IPage.IPagination;

  /** The list of order item entities on this page. */
  data: IOrderItem[];
};
