import { IPage } from "./IPage";
import { IChannel } from "./IChannel";

/**
 * Paginated result set container for Channel search/listing APIs. Returns both
 * the pagination metadata (see IPage.IPagination) and the current batch of
 * Channel entities as an array. Used in PATCH /channels and related list
 * endpoints.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIChannel = {
  pagination: IPage.IPagination;

  /** Array of channels for this page of results. */
  data: IChannel[];
};
