import { tags } from "typia";

/**
 * IProductSeoMeta is the atomic metadata record for product-level SEO
 * configuration as stored in the product_seo_metas table per product/channel.
 * It provides all required fields for on-page search optimization as detailed
 * in the requirements analysis and database schema.
 *
 * The entity contains a reference to the owning product (product_id) and its
 * channel, along with atomic fields for meta title, description, and
 * tags—enabling rich, multi-channel SEO. Descriptions and keywords are
 * optional, following the Prisma schema. This entity supports audit,
 * compliance, and SEO intelligence use cases across admin/user interfaces,
 * batch export, and analytics. All values are atomic, normalized, and
 * non-derived for full audit traceability.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IProductSeoMeta = {
  /**
   * Primary key. System-generated unique identifier for this product SEO meta
   * record. Maps to id field in product_seo_metas table.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Foreign key reference to the target product row in the products table
   * (products.id).
   *
   * Associates this SEO meta entry with a specific product for e-commerce
   * catalog optimization.
   */
  product_id: string & tags.Format<"uuid">;

  /**
   * Associated channel (site/branding context) for this meta, from
   * channels.id.
   *
   * Multi-channel support is critical for search/SEO customization and
   * compliance as described in the requirements.
   */
  channel_id: string & tags.Format<"uuid">;

  /**
   * SEO title for the product—used in web meta tags and search engine
   * previews.
   *
   * Atomic, not derived, supporting multi-language and custom optimization.
   * Sourced from product_seo_metas.meta_title.
   */
  meta_title: string;

  /**
   * Short description for search and snippet preview purposes. Used by search
   * engines and on-page SEO for relevance scoring.
   *
   * Matches meta_description in product_seo_metas. Optional.
   */
  meta_description?: string;

  /**
   * Comma-separated list of keywords or tags. Used by some search engines and
   * internal search for boosting product match.
   *
   * Originates from meta_keywords column in product_seo_metas. Optional.
   */
  meta_keywords?: string;
};
export namespace IProductSeoMeta {
  /**
   * Paginated and filterable search query object for product SEO meta records
   * (product_seo_metas table).
   *
   * Implements requirement for channel-specific, attribute-specific, and
   * keyword-driven SEO record management and compliance reporting.
   */
  export type IRequest = {
    /** Target product for which to search/retrieve SEO meta records. */
    product_id?: string & tags.Format<"uuid">;

    /**
     * Channel reference for the SEO meta (per-channel optimization of SEO
     * settings, as per multi-site requirements).
     */
    channel_id?: string & tags.Format<"uuid">;

    /**
     * Filter: SEO meta title string (partial or full match).
     *
     * Supports title-based queries for admin/analytics review and content
     * curation.
     */
    meta_title?: string;

    /**
     * Optional filter for the SEO description content. Full-text or
     * substring match for compliance or content review workflows.
     */
    meta_description?: string;

    /**
     * Comma-separated keyword filter or search string. Used for analytic
     * exploration of indexed product meta keywords.
     */
    meta_keywords?: string;

    /** Page number for paged search/result sets. */
    page?: number &
      tags.Type<"int32"> &
      tags.JsonSchemaPlugin<{
        format: "uint32";
      }>;

    /** Number of meta records per page (default 100, max configurable). */
    limit?: number &
      tags.Type<"int32"> &
      tags.JsonSchemaPlugin<{
        format: "uint32";
      }>;
  };

  /**
   * IProductSeoMeta.ICreate defines the creation payload for inserting a new
   * product SEO meta record. Follows the product_seo_metas Prisma schema.
   * Ensures normalization and compliance as required per e-commerce and
   * search optimization business flows. Atomic values only, enforceable
   * constraints on product/channel relationship and field presence.
   */
  export type ICreate = {
    /**
     * Product ID (products.id) this SEO meta is associated with. Required
     * for creating a valid meta entry.
     */
    product_id: string & tags.Format<"uuid">;

    /**
     * Channel ID (channels.id) for which the SEO meta applies. Enables
     * scoped customization for multi-site/catalog SEO.
     */
    channel_id: string & tags.Format<"uuid">;

    /**
     * SEO title to display on search pages and meta tags. Required for
     * insertion.
     */
    meta_title: string;

    /**
     * Optional SEO short description for snippet optimization and crawler
     * integration.
     */
    meta_description?: string;

    /**
     * Comma-separated keywords/tags for SEO. Optional and may be empty if
     * not used by current site/crawl strategy.
     */
    meta_keywords?: string;
  };
}
