import { tags } from "typia";

/**
 * RBAC(역할 기반 접근 제어) Permission 엔티티의 단일 객체 타입. 시스템의 권한 정의 기준으로, rbac_permissions
 * Prisma 테이블의 모든 컬럼을 포함하며, 요구사항의 Permission Matrix 설명 및 세부 필드 정의와 완전히 일치해야
 * 합니다.
 *
 * Code 와 is_builtin 필드는 권한 구분과 정책 관리에 핵심이며, description/created_at/updated_at은
 * 감사와 운영 목적의 관리 메타데이터를 완비합니다.
 *
 * 모든 속성에는 DB 컬럼 주석 및 업무 규칙이 상세히 기술되어야 하며, 단일 권한의 모든 데이터 관점(생성, 정책, 수정, 감사, UI
 * 노출 등)에 대해 중복 없이 명확히 문서화되어야 합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IRbacPermission = {
  /** RBAC 권한 정의의 고유 식별자. Prisma rbac_permissions 테이블의 PK입니다. */
  id: string & tags.Format<"uuid">;

  /**
   * 시스템 내 RBAC 권한을 구분하는 유일 코드. 예시: 'order_create', 'user_data_erase'. 요구사항의
   * Permission Matrix 설계에 따라 개별 atomic 권한을 표현하며, rbac_permissions.code 컬럼
   * 참조합니다.
   *
   * 권한 코드 중복 불가, RBAC 엔진의 권한/역할 연결 기준 값.
   */
  code: string;

  /**
   * 해당 권한의 설명(관리자용/헤더/도움말 텍스트 등). Prisma DB rbac_permissions.description 컬럼
   * 참조. 필수값은 아니나, 정책/관리 UI 제공 시 용이.
   */
  description?: string;

  /**
   * 시스템 기본 권한 여부. rbac_permissions.is_builtin 컬럼 명세. 커스텀 정의 권한 구분에 필요, UI 구분에
   * 도움.
   */
  is_builtin: boolean;

  /** RBAC 권한이 생성된 시점. rbac_permissions.created_at 컬럼에 해당. 컴플라이언스 감사/변경 이력 용도. */
  created_at: string & tags.Format<"date-time">;

  /** 권한 정보가 마지막으로 갱신된 시점. rbac_permissions.updated_at 컬럼에 해당. 설정 이력 관리/감사에 필수. */
  updated_at: string & tags.Format<"date-time">;
};
export namespace IRbacPermission {
  /**
   * RBAC(역할 기반 접근 제어) 권한 조회/검색 요청 DTO. 요구사항(User Architecture)의 'Permission
   * Matrix' 설계에 부합하며 Prisma rbac_permissions 테이블 컬럼 설명을 참조합니다.
   *
   * 권한 관리자의 검색, 필터링, 정렬, 페이징 요청 본문에 활용됩니다.
   *
   * 각 필드별로 행 단위 원자 데이터나 생성/갱신 시점, 내장 권한 여부로 필터링이 가능합니다.
   */
  export type IRequest = {
    /**
     * RBAC 권한의 코드(예: 'order_create', 'user_data_erase'). Prisma
     * rbac_permissions 테이블의 code 컬럼에 해당합니다. 전체 텍스트 검색(부분 일치)이나 필터에 사용됩니다.
     *
     * 주로 관리자 대시보드 및 권한 관리 인터페이스에 사용됩니다.
     */
    code?: string;

    /**
     * RBAC 권한의 텍스트 설명에 대한 필터. rbac_permissions 테이블의 description 컬럼 참조. 관리자와
     * 권한 감독자의 검색에 사용됩니다.
     */
    description?: string;

    /**
     * 시스템 내장 권한인지 여부로 필터할 수 있습니다. rbac_permissions.is_builtin 필드와 매핑됩니다.
     * 시스템 구분 권한과 커스텀 권한 검색 지원 목적입니다.
     */
    is_builtin?: boolean;

    /**
     * 생성 시점 이후 필터. rbac_permissions 테이블의 created_at 컬럼을 기준으로 한 날짜 필드.
     * (ISO8601)
     */
    created_after?: string & tags.Format<"date-time">;

    /**
     * 생성 시점 이전 필터. rbac_permissions 테이블의 created_at 컬럼을 기준으로 한 날짜 필드.
     * (ISO8601)
     */
    created_before?: string & tags.Format<"date-time">;

    /** 페이지 번호. 0 또는 1부터 시작. 기본값 1입니다. */
    page?: number & tags.Type<"int32"> & tags.Minimum<1>;

    /** 페이지당 레코드 개수. 기본값 20, 최대값 100. */
    limit?: number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>;

    /** 정렬 기준 필드. code, created_at, updated_at 지원. */
    sort_by?: "code" | "created_at" | "updated_at";

    /** 정렬 방향. 오름차순(asc)/내림차순(desc). 기본 'desc'. */
    sort_dir?: "asc" | "desc";
  };

  /**
   * 신규 RBAC 권한 생성 시 요청에 사용되는 DTO. rbac_permissions Prisma 테이블 컬럼 정의 및 주석 설명을
   * 참조.
   *
   * Code 는 유일해야 하며 시스템 정책 관리/접근 제어 설정의 기반이 됩니다. description은 선택적이지만 권한 이해/감사에
   * 중요하며, is_builtin은 시스템 자동 권한/사용자 커스텀 권한을 나누는 용도.
   *
   * 요구사항 명세에 따른 업무 규칙을 전부 반영, 생성 실패 시 필드별 오류 메시지도 표준적으로 명시해야 함.
   */
  export type ICreate = {
    /**
     * 신규 RBAC 권한 코드. rbac_permissions.code 컬럼과 1:1. 상세 예시는 'order_create',
     * 'audit_log_read' 등.
     */
    code: string;

    /** 권한 설명. 관리자/감사 담당자가 보기 위한 숙지용. rbac_permissions.description 컬럼. */
    description?: string;

    /**
     * 시스템 내장(Built-in) 권한인지 여부. rbac_permissions.is_builtin 컬럼과 일치. true면
     * 시스템/불변 권한 생성.
     */
    is_builtin: boolean;
  };

  /**
   * RBAC 권한 정보 업데이트 요청의 DTO. rbac_permissions Prisma 스키마와 주석을 참조.
   *
   * Code는 대개 불변(변경 시 정책상 엄격한 감사 필요), is_builtin도 시스템/커스텀 구분에 따라 변경 정책 설정,
   * description 필드는 관리 및 해설 텍스트/도움말 갱신에 주로 활용.
   */
  export type IUpdate = {
    /** 권한 코드(수정 가능할 경우에만). 일반적으로는 커스텀 권한만 변경 가능. rbac_permissions.code. */
    code?: string;

    /** 권한 설명. rbac_permissions.description 컬럼. 주로 도움말/정책 설명을 업데이트할 때 사용. */
    description?: string;

    /**
     * 시스템 권한이면 변경 불가. 커스텀 권한일 경우 변환 가능 여부에 따라 true/false.
     * rbac_permissions.is_builtin.
     */
    is_builtin?: boolean;
  };
}
