import { tags } from "typia";

/**
 * Coupon usage event representing a customer redeeming a coupon (typically via
 * checkout/order). Contains detailed evidence fields, compliance identifiers,
 * references to issuance, target order, usage status, and audit dates. Used for
 * all downstream analytics, refund calculations, fraud prevention, and legal
 * business requirements.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallAiBackendCouponUsage = {
  /**
   * Primary key of the coupon usage record, globally unique. Represents the
   * unique business and audit identity for each coupon usage event, necessary
   * for evidence tracking, rollback, and compliance reporting.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Identifier linking to the coupon issuance entity
   * (shopping_mall_ai_backend_coupon_issuances), indicating which issued
   * coupon was redeemed by the user. Critical for audit chain, eligibility
   * checks, and unique usage policy enforcement.
   */
  shopping_mall_ai_backend_coupon_issuance_id: string & tags.Format<"uuid">;

  /**
   * Customer identity (UUID) who used or attempted to use the coupon. Used
   * for compliance, analytics, personalization, and user-specific policy
   * validation.
   */
  shopping_mall_ai_backend_customer_id: string & tags.Format<"uuid">;

  /**
   * (Nullable) UUID for the order the coupon was used on. Used for
   * audit/query, refund/reversal logic, and linking coupon usage to a
   * specific transaction/event.
   */
  shopping_mall_ai_backend_order_id?: (string & tags.Format<"uuid">) | null;

  /**
   * Date-time (ISO8601) of coupon usage event by the customer. Required for
   * evidence compliance, reporting, and business rules on when usage
   * occurred.
   */
  used_at: string & tags.Format<"date-time">;

  /**
   * Monetary discount value applied for this coupon usage (in coupon's
   * currency if specified). Required for analytics, actual cost to business,
   * and refunds.
   */
  amount_discounted: number;

  /**
   * Business usage status: e.g., 'success', 'failed', 'revoked',
   * 'rolled_back'. Used for business/audit review, compliance investigation,
   * and system health tracking.
   */
  status: string;

  /**
   * Timestamp when this usage was rolled back/refunded/canceled, if
   * applicable. Enables evidence-based tracking of reversal actions for
   * compliance and audit.
   */
  rolledback_at?: (string & tags.Format<"date-time">) | null;
};
export namespace IShoppingMallAiBackendCouponUsage {
  /**
   * Advanced filter/search payload for reviewing coupon usage. Includes
   * status, specific customer, coupon, usage dates, and pagination.
   */
  export type IRequest = {
    /** Usage status: success, failed, revoked, etc. */
    status?: string;
    shopping_mall_ai_backend_customer_id?: string & tags.Format<"uuid">;
    shopping_mall_ai_backend_coupon_id?: string & tags.Format<"uuid">;
    used_at_from?: string & tags.Format<"date-time">;
    used_at_to?: string & tags.Format<"date-time">;
    page?: number & tags.Type<"int32">;
    limit?: number & tags.Type<"int32">;
  };
}
