import { tags } from "typia";

/**
 * Coupon campaign entity. Represents a campaign grouping one or more coupons
 * under a business concept. Contains metadata, business status, scheduling
 * fields, and audit trail fields. Directly associated with the
 * 'shopping_mall_coupon_campaigns' table.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallCouponCampaign = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /** Business-facing campaign name. */
  name: string;

  /** Campaign description and terms. */
  description?: string | null | undefined;

  /** Campaign activation/start time. */
  starts_at?: (string & tags.Format<"date-time">) | null | undefined;

  /** Campaign end/expiration time. */
  ends_at?: (string & tags.Format<"date-time">) | null | undefined;

  /** Workflow status: draft, active, paused, expired, deleted, etc. */
  business_status: string;

  /** Campaign creation timestamp. */
  created_at: string & tags.Format<"date-time">;

  /** Campaign update timestamp. */
  updated_at: string & tags.Format<"date-time">;

  /** Logical deletion timestamp, for partitioning and audit. */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IShoppingMallCouponCampaign {
  /**
   * Advanced search and filter criteria for coupon campaign listing. Allows
   * filtering by campaign name (partial), business status, date ranges, and
   * pagination controls. Used in admin UI and campaign analytics.
   */
  export type IRequest = {
    /** Filter for campaign name (supports partial match). */
    name?: string | undefined;

    /** Search filter by campaign workflow status. */
    business_status?: string | undefined;

    /** Filter for campaign start after this date (inclusive). */
    starts_at_from?: (string & tags.Format<"date-time">) | undefined;

    /** Filter for campaign start before this date (inclusive). */
    starts_at_to?: (string & tags.Format<"date-time">) | undefined;

    /** Filter for campaign end after this date (inclusive). */
    ends_at_from?: (string & tags.Format<"date-time">) | undefined;

    /** Filter for campaign end before this date (inclusive). */
    ends_at_to?: (string & tags.Format<"date-time">) | undefined;

    /** Current page number (pagination). */
    page?: (number & tags.Type<"int32">) | undefined;

    /** Records per page (pagination). */
    limit?: (number & tags.Type<"int32">) | undefined;
  };

  /**
   * Creation DTO for a coupon campaign. Used to register a new coupon
   * campaign in the shopping mall system. Matches the business and audit
   * fields in 'shopping_mall_coupon_campaigns'.
   */
  export type ICreate = {
    /** Business-facing campaign name. */
    name: string;

    /** Campaign description and terms. */
    description?: string | null | undefined;

    /** Campaign activation/start time. */
    starts_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Campaign end/expiration time. */
    ends_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Workflow status: draft, active, paused, expired, deleted, etc. */
    business_status: string;
  };

  /**
   * DTO for updating a coupon campaign. Allows modifications to name,
   * description, active window, and status. Maps to editable properties in
   * shopping_mall_coupon_campaigns. All fields are for campaign-level
   * metadata, not for coupon logic. Dates must be ISO 8601. Status must
   * follow enum values in business logic.
   */
  export type IUpdate = {
    /** Business-facing campaign name. */
    name: string;

    /** Campaign description and terms. */
    description?: string | null | undefined;

    /**
     * Activation/start time for coupon campaign (ISO 8601). If null,
     * campaign has no set start.
     */
    starts_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * End/expiration time for coupon campaign (ISO 8601). If null, campaign
     * is indefinitely open.
     */
    ends_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Workflow status: draft, active, paused, expired, deleted, etc. */
    business_status: string;
  };

  /**
   * Summary of a shopping mall coupon campaign. Used for campaign
   * listing/search with key status, period, and identity fields. Excludes
   * deep analytics and coupon relations. Aligned with
   * shopping_mall_coupon_campaigns schema.
   */
  export type ISummary = {
    /**
     * Primary Key.
     *
     * Unique identifier for the campaign.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Business-facing campaign name. Must be unique per DB constraint.
     * Primary UI label.
     */
    name: string;

    /**
     * Datetime when campaign begins; null means immediately active or
     * system default.
     */
    starts_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Expiration/end datetime for the campaign. Null means no planned
     * expiration.
     */
    ends_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Campaign business status or workflow indicator. Examples: draft,
     * active, paused, expired, deleted. Used for filtering, dashboard, and
     * automation.
     */
    business_status: string;
  };
}
