import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallOrderSnapshot } from "../../../../../structures/IShoppingMallOrderSnapshot";
import { IPageIShoppingMallOrderSnapshot } from "../../../../../structures/IPageIShoppingMallOrderSnapshot";

/**
 * List paginated order snapshot history for a specific order
 * (shopping_mall_order_snapshots).
 *
 * Use this endpoint to retrieve a filtered and paginated list of all historical
 * state snapshots for a specific order. Snapshots are created on each key state
 * transition for shopping_mall_orders, preserving the complete serialized order
 * object for audit, compliance, and evidence purposes.
 *
 * Request body supports advanced search, pagination, and sorting capabilities,
 * using IShoppingMallOrderSnapshot.IRequest to specify filters such as snapshot
 * event time, snapshot_reason, or actor. The response is a paginated list of
 * snapshots (IPageIShoppingMallOrderSnapshot), facilitating legal, audit, and
 * business investigations.
 *
 * Authorization checks allow access for order owners (customers), relevant
 * sellers, and platform admins. Sensitive details are filtered according to
 * role permissions, supporting regional compliance regulations.
 *
 * @param props.connection
 * @param props.orderId Identifier of the order to retrieve snapshots for (UUID)
 * @param props.body Filtering, sorting, and pagination parameters for order
 *   snapshot retrieval
 * @path /shoppingMall/admin/orders/:orderId/snapshots
 * @accessor api.functional.shoppingMall.admin.orders.snapshots.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Identifier of the order to retrieve snapshots for (UUID) */
    orderId: string & tags.Format<"uuid">;

    /**
     * Filtering, sorting, and pagination parameters for order snapshot
     * retrieval
     */
    body: IShoppingMallOrderSnapshot.IRequest;
  };
  export type Body = IShoppingMallOrderSnapshot.IRequest;
  export type Response = IPageIShoppingMallOrderSnapshot;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/admin/orders/:orderId/snapshots",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/admin/orders/${encodeURIComponent(props.orderId ?? "null")}/snapshots`;
  export const random = (): IPageIShoppingMallOrderSnapshot =>
    typia.random<IPageIShoppingMallOrderSnapshot>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a single historical snapshot of an order for audit and evidence
 * purposes (shopping_mall_order_snapshots).
 *
 * This operation allows authorized users (such as administrators or the
 * customer who placed the order) to fetch a single snapshot of an order record
 * based on a snapshot's unique identifier. Each snapshot preserves the
 * immutable state of the order at the moment of a critical business event (such
 * as creation, payment, shipment, cancellation, etc).
 *
 * Security: Only users with rights over the order (the owner, the fulfilling
 * seller, or a system admin) may access the snapshot, as it may contain PII and
 * sensitive transactional data. Permission checks must verify the requesting
 * user's relationship to the order before serving the snapshot.
 *
 * The response includes all key order fields and nested data (items, payments,
 * fulfillment, etc.) serialized as at the snapshot time, suitable for
 * compliance export or internal forensic analysis.
 *
 * Linked DB: shopping_mall_order_snapshots, with foreign key to
 * shopping_mall_orders. This is part of the audit/evidence chain for order
 * lifecycle events. Path parameter 'orderId' is required for context, and
 * 'snapshotId' identifies the exact snapshot entity.
 *
 * If the order or snapshot does not exist (or the user has insufficient
 * rights), the system returns HTTP 404 or 403 with an error message in
 * accordance with compliance and privacy standards.
 *
 * @param props.connection
 * @param props.orderId UUID of the target order whose snapshot is being
 *   requested.
 * @param props.snapshotId UUID of the snapshot record to retrieve, uniquely
 *   identifying the historical record.
 * @path /shoppingMall/admin/orders/:orderId/snapshots/:snapshotId
 * @accessor api.functional.shoppingMall.admin.orders.snapshots.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** UUID of the target order whose snapshot is being requested. */
    orderId: string & tags.Format<"uuid">;

    /**
     * UUID of the snapshot record to retrieve, uniquely identifying the
     * historical record.
     */
    snapshotId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallOrderSnapshot;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/admin/orders/:orderId/snapshots/:snapshotId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/admin/orders/${encodeURIComponent(props.orderId ?? "null")}/snapshots/${encodeURIComponent(props.snapshotId ?? "null")}`;
  export const random = (): IShoppingMallOrderSnapshot =>
    typia.random<IShoppingMallOrderSnapshot>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
      assert.param("snapshotId")(() => typia.assert(props.snapshotId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
