import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";

import { IPageIAimallBackendCategory } from "../../../../api/structures/IPageIAimallBackendCategory";
import { IAimallBackendCategory } from "../../../../api/structures/IAimallBackendCategory";

@Controller("/aimall-backend/seller/categories")
export class Aimall_backendSellerCategoriesController {
  /**
   * List all product categories for taxonomy management and selection.
   *
   * Fetches all product taxonomy categories. Response includes all categories
   * and their hierarchical context (parent_id, depth, name). Data is strictly
   * normalized; no product or summary data is included. Useful for populating
   * category selectors or displaying the product taxonomy. If paginated,
   * response structure is IPageIAimallBackendCategory. Permissions: available
   * to all customers, sellers, or administrators; administrators may see
   * hidden/system categories as well by additional filtering if supported.
   *
   * @param connection
   * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
   */
  @TypedRoute.Get()
  public async index(): Promise<IPageIAimallBackendCategory> {
    return typia.random<IPageIAimallBackendCategory>();
  }

  /**
   * Create new product category for taxonomy expansion.
   *
   * Creates a new product taxonomy category. Input includes required atomic
   * fields, guaranteeing category normalization per schema. Validation
   * applies for unique parent/name pair for hierarchical compliance. Only
   * accessible to authorized sellers or administrators responsible for
   * category management. Returns created record as confirmation, or 422/403
   * on error.
   *
   * @param connection
   * @param body Category definition data (name, parent_id, depth, etc.)
   *   required for creation.
   * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
   */
  @TypedRoute.Post()
  public async create(
    @TypedBody()
    body: IAimallBackendCategory.ICreate,
  ): Promise<IAimallBackendCategory> {
    body;
    return typia.random<IAimallBackendCategory>();
  }

  /**
   * Search or filter paginated categories for admin or advanced user
   * scenarios.
   *
   * Retrieves a filtered and paginated list of product categories according
   * to supplied query parameters. Allows advanced search on category name,
   * depth, or parent_id. Response contains page of categories and supports
   * sorting configuration. Used by administrators or catalog managers in
   * taxonomy administration. Returns 403 for forbidden, 422 for invalid
   * parameters. Security: customer, seller, or administrator role required.
   *
   * @param connection
   * @param body Filter/search parameters for querying categories, including
   *   pagination, keyword, and sort settings.
   * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
   */
  @TypedRoute.Patch()
  public async search(
    @TypedBody()
    body: IAimallBackendCategory.IRequest,
  ): Promise<IPageIAimallBackendCategory> {
    body;
    return typia.random<IPageIAimallBackendCategory>();
  }

  /**
   * Fetch one category by its ID for detailed viewing or update.
   *
   * Retrieves details for a specific product category, returning all atomic
   * fields (name, depth, parent_id). Returns 404 if not found. Permissions:
   * customer, seller, or administrator as appropriate for catalog access.
   * Error scenarios include non-existent ID, lack of permission, or database
   * error.
   *
   * @param connection
   * @param categoryId Unique identifier of the product category.
   * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
   */
  @TypedRoute.Get(":categoryId")
  public async at(
    @TypedParam("categoryId")
    categoryId: string & tags.Format<"uuid">,
  ): Promise<IAimallBackendCategory> {
    categoryId;
    return typia.random<IAimallBackendCategory>();
  }

  /**
   * Update fields of a single category by ID.
   *
   * Updates the fields of a category by its unique identifier. Supports
   * updating name, parent_id, or depth as allowed by business logic and
   * schema. Administrator or seller privileges are required. Returns updated
   * entity. Errors include 404 if not found, 403 if unauthorized, 422 if
   * validation fails. Can be chained with GET by ID for edit forms.
   *
   * @param connection
   * @param categoryId Unique ID of the category to update.
   * @param body Fields allowed for category update (name, parent_id, etc.)
   * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
   */
  @TypedRoute.Put(":categoryId")
  public async update(
    @TypedParam("categoryId")
    categoryId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IAimallBackendCategory.IUpdate,
  ): Promise<IAimallBackendCategory> {
    categoryId;
    body;
    return typia.random<IAimallBackendCategory>();
  }

  /**
   * Hard delete a product category by ID.
   *
   * Deletes (hard, irreversible) a product category record, removing it from
   * taxonomy. Before deletion, dependency checks must be enforced (e.g., no
   * related products exist/child categories reassigned) to avoid orphaned
   * references. Returns 204 (no content) on success or 404 if not found. Only
   * available to users with appropriate permissions (seller, administrator).
   *
   * @param connection
   * @param categoryId ID of the category to delete.
   * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
   */
  @TypedRoute.Delete(":categoryId")
  public async erase(
    @TypedParam("categoryId")
    categoryId: string & tags.Format<"uuid">,
  ): Promise<void> {
    categoryId;
    return typia.random<void>();
  }
}
