import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IAiCommerceProductAuditLog } from "../../../../../structures/IAiCommerceProductAuditLog";
import { IPageIAiCommerceProductAuditLog } from "../../../../../structures/IPageIAiCommerceProductAuditLog";

/**
 * Search and retrieve audit logs of a product (ai_commerce_product_audit_logs).
 *
 * This operation allows authorized sellers or admins to review the complete
 * audit history for a product, using advanced search, filter, and pagination
 * parameters passed in IAiCommerceProductAuditLog.IRequest. The endpoint
 * returns IPageIAiCommerceProductAuditLog, detailing each audit event, its
 * source/actor, what changed, and when.
 *
 * All accesses must be logged as read operations for compliance. No data is
 * modified by this method. Audit logs are critical for legal compliance,
 * security, forensic analysis, and dispute investigations, so business logic
 * must ensure only properly authorized users have access. When requested,
 * highly sensitive or private changes may be subject to further masking or
 * redaction based on platform compliance policy.
 *
 * @param props.connection
 * @param props.productId UUID of the product whose audit logs will be
 *   retrieved.
 * @param props.body Advanced filtering and pagination options for product audit
 *   logs retrieval.
 * @path /aiCommerce/seller/products/:productId/auditLogs
 * @accessor api.functional.aiCommerce.seller.products.auditLogs.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** UUID of the product whose audit logs will be retrieved. */
    productId: string & tags.Format<"uuid">;

    /**
     * Advanced filtering and pagination options for product audit logs
     * retrieval.
     */
    body: IAiCommerceProductAuditLog.IRequest;
  };
  export type Body = IAiCommerceProductAuditLog.IRequest;
  export type Response = IPageIAiCommerceProductAuditLog;

  export const METADATA = {
    method: "PATCH",
    path: "/aiCommerce/seller/products/:productId/auditLogs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/aiCommerce/seller/products/${encodeURIComponent(props.productId ?? "null")}/auditLogs`;
  export const random = (): IPageIAiCommerceProductAuditLog =>
    typia.random<IPageIAiCommerceProductAuditLog>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
