import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IPageIAimallBackendCategory } from "../../../../structures/IPageIAimallBackendCategory";
import { IAimallBackendCategory } from "../../../../structures/IAimallBackendCategory";
export * as childCategories from "./childCategories";

/**
 * List all product categories for taxonomy management and selection.
 *
 * Fetches all product taxonomy categories. Response includes all categories and
 * their hierarchical context (parent_id, depth, name). Data is strictly
 * normalized; no product or summary data is included. Useful for populating
 * category selectors or displaying the product taxonomy. If paginated, response
 * structure is IPageIAimallBackendCategory. Permissions: available to all
 * customers, sellers, or administrators; administrators may see hidden/system
 * categories as well by additional filtering if supported.
 *
 * @param props.connection
 * @path /aimall-backend/seller/categories
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(connection: IConnection): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
      );
}
export namespace index {
  export type Response = IPageIAimallBackendCategory;

  export const METADATA = {
    method: "GET",
    path: "/aimall-backend/seller/categories",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/aimall-backend/seller/categories";
  export const random = (): IPageIAimallBackendCategory =>
    typia.random<IPageIAimallBackendCategory>();
  export const simulate = (_connection: IConnection): Response => {
    return random();
  };
}

/**
 * Create new product category for taxonomy expansion.
 *
 * Creates a new product taxonomy category. Input includes required atomic
 * fields, guaranteeing category normalization per schema. Validation applies
 * for unique parent/name pair for hierarchical compliance. Only accessible to
 * authorized sellers or administrators responsible for category management.
 * Returns created record as confirmation, or 422/403 on error.
 *
 * @param props.connection
 * @param props.body Category definition data (name, parent_id, depth, etc.)
 *   required for creation.
 * @path /aimall-backend/seller/categories
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Category definition data (name, parent_id, depth, etc.) required for
     * creation.
     */
    body: IAimallBackendCategory.ICreate;
  };
  export type Body = IAimallBackendCategory.ICreate;
  export type Response = IAimallBackendCategory;

  export const METADATA = {
    method: "POST",
    path: "/aimall-backend/seller/categories",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/aimall-backend/seller/categories";
  export const random = (): IAimallBackendCategory =>
    typia.random<IAimallBackendCategory>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Search or filter paginated categories for admin or advanced user scenarios.
 *
 * Retrieves a filtered and paginated list of product categories according to
 * supplied query parameters. Allows advanced search on category name, depth, or
 * parent_id. Response contains page of categories and supports sorting
 * configuration. Used by administrators or catalog managers in taxonomy
 * administration. Returns 403 for forbidden, 422 for invalid parameters.
 * Security: customer, seller, or administrator role required.
 *
 * @param props.connection
 * @param props.body Filter/search parameters for querying categories, including
 *   pagination, keyword, and sort settings.
 * @path /aimall-backend/seller/categories
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function search(
  connection: IConnection,
  props: search.Props,
): Promise<search.Response> {
  return true === connection.simulate
    ? search.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...search.METADATA,
          path: search.path(),
          status: null,
        },
        props.body,
      );
}
export namespace search {
  export type Props = {
    /**
     * Filter/search parameters for querying categories, including
     * pagination, keyword, and sort settings.
     */
    body: IAimallBackendCategory.IRequest;
  };
  export type Body = IAimallBackendCategory.IRequest;
  export type Response = IPageIAimallBackendCategory;

  export const METADATA = {
    method: "PATCH",
    path: "/aimall-backend/seller/categories",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/aimall-backend/seller/categories";
  export const random = (): IPageIAimallBackendCategory =>
    typia.random<IPageIAimallBackendCategory>();
  export const simulate = (
    connection: IConnection,
    props: search.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: search.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Fetch one category by its ID for detailed viewing or update.
 *
 * Retrieves details for a specific product category, returning all atomic
 * fields (name, depth, parent_id). Returns 404 if not found. Permissions:
 * customer, seller, or administrator as appropriate for catalog access. Error
 * scenarios include non-existent ID, lack of permission, or database error.
 *
 * @param props.connection
 * @param props.categoryId Unique identifier of the product category.
 * @path /aimall-backend/seller/categories/:categoryId
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the product category. */
    categoryId: string & tags.Format<"uuid">;
  };
  export type Response = IAimallBackendCategory;

  export const METADATA = {
    method: "GET",
    path: "/aimall-backend/seller/categories/:categoryId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/aimall-backend/seller/categories/${encodeURIComponent(props.categoryId ?? "null")}`;
  export const random = (): IAimallBackendCategory =>
    typia.random<IAimallBackendCategory>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("categoryId")(() => typia.assert(props.categoryId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update fields of a single category by ID.
 *
 * Updates the fields of a category by its unique identifier. Supports updating
 * name, parent_id, or depth as allowed by business logic and schema.
 * Administrator or seller privileges are required. Returns updated entity.
 * Errors include 404 if not found, 403 if unauthorized, 422 if validation
 * fails. Can be chained with GET by ID for edit forms.
 *
 * @param props.connection
 * @param props.categoryId Unique ID of the category to update.
 * @param props.body Fields allowed for category update (name, parent_id, etc.)
 * @path /aimall-backend/seller/categories/:categoryId
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** Unique ID of the category to update. */
    categoryId: string & tags.Format<"uuid">;

    /** Fields allowed for category update (name, parent_id, etc.) */
    body: IAimallBackendCategory.IUpdate;
  };
  export type Body = IAimallBackendCategory.IUpdate;
  export type Response = IAimallBackendCategory;

  export const METADATA = {
    method: "PUT",
    path: "/aimall-backend/seller/categories/:categoryId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/aimall-backend/seller/categories/${encodeURIComponent(props.categoryId ?? "null")}`;
  export const random = (): IAimallBackendCategory =>
    typia.random<IAimallBackendCategory>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("categoryId")(() => typia.assert(props.categoryId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Hard delete a product category by ID.
 *
 * Deletes (hard, irreversible) a product category record, removing it from
 * taxonomy. Before deletion, dependency checks must be enforced (e.g., no
 * related products exist/child categories reassigned) to avoid orphaned
 * references. Returns 204 (no content) on success or 404 if not found. Only
 * available to users with appropriate permissions (seller, administrator).
 *
 * @param props.connection
 * @param props.categoryId ID of the category to delete.
 * @path /aimall-backend/seller/categories/:categoryId
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** ID of the category to delete. */
    categoryId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/aimall-backend/seller/categories/:categoryId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/aimall-backend/seller/categories/${encodeURIComponent(props.categoryId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("categoryId")(() => typia.assert(props.categoryId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
