import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IAiCommerceProductTag } from "../../../../structures/IAiCommerceProductTag";

/**
 * Create a new product-tag binding (ai_commerce_product_tags).
 *
 * Create a new product-tag binding in the ai_commerce_product_tags table. This
 * operation links a tag to a product, enhancing search/discovery features and
 * supporting marketing or analytic initiatives.
 *
 * The input includes identifiers for both product and tag, and may also include
 * meta or business context. Permissions apply: sellers can only tag their own
 * products; admins can create any binding. Error scenarios are duplicate
 * bindings, non-existent product/tag, or permission errors.
 *
 * @param props.connection
 * @param props.body The product-tag binding creation payload with product, tag,
 *   and context info.
 * @path /aiCommerce/seller/productTags
 * @accessor api.functional.aiCommerce.seller.productTags.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * The product-tag binding creation payload with product, tag, and
     * context info.
     */
    body: IAiCommerceProductTag.ICreate;
  };
  export type Body = IAiCommerceProductTag.ICreate;
  export type Response = IAiCommerceProductTag;

  export const METADATA = {
    method: "POST",
    path: "/aiCommerce/seller/productTags",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/aiCommerce/seller/productTags";
  export const random = (): IAiCommerceProductTag =>
    typia.random<IAiCommerceProductTag>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing product-tag binding (ai_commerce_product_tags).
 *
 * Update an existing product-tag binding in ai_commerce_product_tags. This is
 * used to reclassify the tag or product association, update meta/context info,
 * or correct earlier mistakes. Only admins or the owning seller may perform
 * this action.
 *
 * All changes are tracked and auditable for compliance and analytics history.
 * The operation requires the unique productTagId, and the request body details
 * the fields to update. Security: Only permitted users may update their own
 * products' tag bindings; error handling includes lack of permission, invalid
 * IDs, or data conflicts.
 *
 * @param props.connection
 * @param props.productTagId The unique identifier of the product-tag binding to
 *   update.
 * @param props.body Updated fields for the product-tag binding.
 * @path /aiCommerce/seller/productTags/:productTagId
 * @accessor api.functional.aiCommerce.seller.productTags.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** The unique identifier of the product-tag binding to update. */
    productTagId: string & tags.Format<"uuid">;

    /** Updated fields for the product-tag binding. */
    body: IAiCommerceProductTag.IUpdate;
  };
  export type Body = IAiCommerceProductTag.IUpdate;
  export type Response = IAiCommerceProductTag;

  export const METADATA = {
    method: "PUT",
    path: "/aiCommerce/seller/productTags/:productTagId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/aiCommerce/seller/productTags/${encodeURIComponent(props.productTagId ?? "null")}`;
  export const random = (): IAiCommerceProductTag =>
    typia.random<IAiCommerceProductTag>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productTagId")(() => typia.assert(props.productTagId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Erase a product-tag binding (ai_commerce_product_tags).
 *
 * Delete (erase) a product-tag binding from the ai_commerce_product_tags table.
 * This removes the tag-product association, affecting search/discovery on the
 * platform. Only admins or owners can perform this.
 *
 * The operation takes the unique productTagId. Once erased, the association is
 * lost and cannot be immediately recovered unless re-created. Compliance and
 * audit logging applies. Errors include invalid binding ID, insufficient
 * permissions, or attempting to delete protected/tagged associations.
 *
 * @param props.connection
 * @param props.productTagId The unique identifier of the product-tag binding to
 *   erase.
 * @path /aiCommerce/seller/productTags/:productTagId
 * @accessor api.functional.aiCommerce.seller.productTags.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** The unique identifier of the product-tag binding to erase. */
    productTagId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/aiCommerce/seller/productTags/:productTagId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/aiCommerce/seller/productTags/${encodeURIComponent(props.productTagId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productTagId")(() => typia.assert(props.productTagId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
