import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallCartItem } from "../../../../../structures/IShoppingMallCartItem";
import { IPageIShoppingMallCartItem } from "../../../../../structures/IPageIShoppingMallCartItem";

/**
 * List and search all items in a specific cart (paginated, filterable;
 * shopping_mall_cart_items).
 *
 * Retrieves the complete list of items currently held within a specific
 * shopping cart, enabling the customer or authorized admin roles to see,
 * search, sort, or paginate through the cart's contents. Advanced filtering can
 * be applied based on product or variant, added time, or grouping labels when
 * batch features are enabled.
 *
 * The list is always scoped to a single cart via cartId, guaranteeing isolation
 * and privacy between different users' carts. The operation integrates deep
 * business rules, ensuring real-time item data consistency with catalog status,
 * inventory, or product updates (e.g., out-of-stock products appear as inactive
 * items). Results can support batch selection (for example, for mass removal or
 * checkout), with UI-level pagination and sorting options.
 *
 * This endpoint ties directly into the cart/checkout workflow and supports
 * personalization/AI modules by providing comprehensive insight into in-session
 * cart activity. Error cases include invalid cartId, unauthorized access, or
 * filtering by fields that do not exist on cart items.
 *
 * @param props.connection
 * @param props.cartId Unique identifier for the cart whose items are to be
 *   listed.
 * @param props.body Search, filter, and paging parameters for the cart items
 *   within the given cart.
 * @path /shoppingMall/admin/carts/:cartId/items
 * @accessor api.functional.shoppingMall.admin.carts.items.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Unique identifier for the cart whose items are to be listed. */
    cartId: string & tags.Format<"uuid">;

    /**
     * Search, filter, and paging parameters for the cart items within the
     * given cart.
     */
    body: IShoppingMallCartItem.IRequest;
  };
  export type Body = IShoppingMallCartItem.IRequest;
  export type Response = IPageIShoppingMallCartItem;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/admin/carts/:cartId/items",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/admin/carts/${encodeURIComponent(props.cartId ?? "null")}/items`;
  export const random = (): IPageIShoppingMallCartItem =>
    typia.random<IPageIShoppingMallCartItem>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("cartId")(() => typia.assert(props.cartId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a single cart item with product and variant detail
 * (shopping_mall_cart_items).
 *
 * Fetches full details for a single item within a user's cart, using both
 * cartId and cartItemId to guarantee ownership and path-union context. The
 * returned information covers core relationships: the product, selected
 * variant, quantity, and relevant option/variant selections, along with the
 * added timestamp and current status (including inactive or invalid if product
 * status changed since addition).
 *
 * Security and business requirements ensure that only the owner or authorized
 * admin roles may access this resource. The endpoint returns up-to-date product
 * and variant metadata reflecting any catalog status, price, or availability
 * changes at the time of request—critical for checkout validation. Error
 * handling addresses cases such as missing or deleted cart or item, or
 * cross-user access attempts.
 *
 * This endpoint is an integral part of user session and checkout flows,
 * supporting UI and personalization logic, and adheres closely to
 * shopping_mall_cart_items table constraints documented in the Prisma schema.
 *
 * @param props.connection
 * @param props.cartId Parent cart ID for ownership and access scoping.
 * @param props.cartItemId Cart item ID to identify the record to retrieve.
 * @path /shoppingMall/admin/carts/:cartId/items/:cartItemId
 * @accessor api.functional.shoppingMall.admin.carts.items.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Parent cart ID for ownership and access scoping. */
    cartId: string & tags.Format<"uuid">;

    /** Cart item ID to identify the record to retrieve. */
    cartItemId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallCartItem;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/admin/carts/:cartId/items/:cartItemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/admin/carts/${encodeURIComponent(props.cartId ?? "null")}/items/${encodeURIComponent(props.cartItemId ?? "null")}`;
  export const random = (): IShoppingMallCartItem =>
    typia.random<IShoppingMallCartItem>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("cartId")(() => typia.assert(props.cartId));
      assert.param("cartItemId")(() => typia.assert(props.cartItemId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
